arch:
    - amd64
    - ppc64le
language: ruby
cache: bundler
bundler_args: --without development
sudo: false

rvm:
  - 2.5
  - 2.6
  - 2.7
  - jruby

gemfile:
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_master.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby
    - gemfile: gemfiles/activerecord_master.gemfile
